PackageIdentifier: cccadet.omni-sql
PackageVersion: 0.5.2
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
ProductCode: omni-sql
AppsAndFeaturesEntries:
  - DisplayName: omni-sql
    DisplayVersion: 0.5.2
    Publisher: omnisql
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/cccadet/omni-sql/releases/download/v0.5.2/omni-sql_0.5.2_x64-setup.exe
    InstallerSha256: 0AA09D74C3B6E3EB2F8C19C04DF087E3A7D5764C2840B695A3B10058108001C7
ManifestType: installer
ManifestVersion: 1.12.0
