-- H2 (JDBC genérico): mesmo schema/dados dos demais bancos de teste.
-- Executado pelo serviço h2-init via org.h2.tools.RunScript (ver docker-compose.yml).
--
-- Sem a função get_customer_total: H2 2.x não tem funções SQL-bodied, e o
-- JdbcAdapter não introspeciona funções/índices/definições por design
-- (DatabaseMetaData não é confiável entre drivers JDBC arbitrários) — os
-- testes correspondentes são pulados para este alvo.

DROP VIEW IF EXISTS order_summary;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;

-- ── Tabelas ──

CREATE TABLE customers (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    email       VARCHAR(200) UNIQUE NOT NULL,
    city        VARCHAR(100),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    price       NUMERIC(10, 2) NOT NULL,
    category    VARCHAR(50)
);

CREATE TABLE orders (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INT NOT NULL REFERENCES customers(id),
    order_date  DATE DEFAULT CURRENT_DATE,
    total       NUMERIC(12, 2)
);

CREATE TABLE order_items (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INT NOT NULL REFERENCES orders(id),
    product_id  INT NOT NULL REFERENCES products(id),
    quantity    INT NOT NULL DEFAULT 1,
    unit_price  NUMERIC(10, 2) NOT NULL
);

-- ── Dados (idênticos aos demais bancos) ──

INSERT INTO customers (name, email, city) VALUES
    ('Alice Silva',   'alice@example.com',  'São Paulo'),
    ('Bob Santos',    'bob@example.com',    'Rio de Janeiro'),
    ('Carol Oliveira','carol@example.com',  'Belo Horizonte'),
    ('Dave Pereira',  'dave@example.com',   'Curitiba'),
    ('Eve Lima',      'eve@example.com',    'Porto Alegre');

INSERT INTO products (name, price, category) VALUES
    ('Notebook Pro',    4999.90, 'Eletrônicos'),
    ('Mouse Wireless',   129.90, 'Eletrônicos'),
    ('Cadeira Ergo',    1299.00, 'Mobília'),
    ('Monitor 27"',     2199.00, 'Eletrônicos'),
    ('Teclado Mec',      349.90, 'Eletrônicos');

INSERT INTO orders (customer_id, order_date, total) VALUES
    (1, '2026-01-15', 5129.80),
    (2, '2026-02-20', 1648.90),
    (1, '2026-03-10', 349.90),
    (3, '2026-04-05', 7198.80),
    (4, '2026-05-12', 129.90);

INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES
    (1, 1, 1, 4999.90),
    (1, 2, 1,  129.90),
    (2, 3, 1, 1299.00),
    (2, 5, 1,  349.90),
    (3, 5, 1,  349.90),
    (4, 4, 2, 2199.00),
    (4, 2, 1,  129.90),
    (5, 2, 1,  129.90);

-- ── Índices ──

CREATE INDEX idx_orders_customer ON orders(customer_id);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE UNIQUE INDEX idx_customers_email ON customers(email);

-- ── View ──

CREATE VIEW order_summary AS
SELECT
    o.id AS order_id,
    c.name AS customer_name,
    c.city,
    o.order_date,
    o.total,
    (SELECT COUNT(*) FROM order_items oi WHERE oi.order_id = o.id) AS item_count
FROM orders o
JOIN customers c ON c.id = o.customer_id;
